# Generated by Django 4.2.7 on 2023-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
